spring:
  application:
    name: lockers-api
  datasource:
    url: jdbc:postgresql://localhost:5432/lockers-db
    username: admin-lockers
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      jdbc:
        batch_size: 30
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    clean-disabled: true
    clean-on-validation-error: true